### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-PDF/xrdphase#5]
It seems `scikit-learn` should be a dependency. @AbbyGi, could you please update the file with all the dependencies? Thanks.

**Comment by mrakitin** [comment]
That's a list I've found so far based on imports in the code:
- ipython
- fire
- ipywidgets
- matplotlib
- numpy
- pandas
- pymatgen
- scipy
- sklearn

**Comment by AbbyGi** [comment]
Requirement files have been updated.

**Comment by mrakitin** [comment]
Thanks @AbbyGi! Could you please provide a link to the commit with the changes? Ideally the fix should go through a pull request (PR), so that we can review/test it before it gets merged. Please stop by if you would like to learn more about git, will be happy to assist.

**Comment by AbbyGi** [comment]
https://github.com/NSLS-II-PDF/xrdphase/commit/7e711287349414a7c26b487976f19742fb45f92a and https://github.com/NSLS-II-PDF/xrdphase/commit/0c5ed4da2d82026b5e626265242ddf401aea71be are the initial commits. https://github.com/NSLS-II-PDF/xrdphase/commit/54c484fc4178b1c1ea2a8ff667f5e047431c9557 is the commit that removes pickle from the requirements file.
